# Generated by Django 6.0 on 2026-05-30 11:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emr', '0077_tagconfig_metadata'),
        ('facility', '0484_remove_facility_discount_codes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EAushadhiFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('inward_date', models.DateField()),
                ('triggered_by', models.CharField(choices=[('USER', 'User'), ('CRON', 'Cron'), ('RETRY', 'Retry')], default='USER', max_length=20)),
                ('fetch_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=20)),
                ('http_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('api_response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('total_items_in_response', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eaushadhi_fetch_logs', to='facility.facility')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'E-Aushadhi Fetch Logs',
            },
        ),
        migrations.CreateModel(
            name='EAushadhiInwardRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('inward_date', models.DateField()),
                ('sync_status', models.CharField(choices=[('NEVER_SYNCED', 'Never Synced'), ('FRESH', 'Fresh'), ('STALE', 'Stale'), ('SYNCING', 'Syncing'), ('FAILED', 'Failed')], default='NEVER_SYNCED', max_length=20)),
                ('items_initial_count', models.PositiveIntegerField(blank=True, null=True)),
                ('items_current_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eaushadhi_inward_records', to='facility.facility')),
                ('last_attempted_fetch_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempted_inward_records', to='care_eaushadhi.eaushadhifetchlog')),
                ('last_successful_fetch_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successful_inward_records', to='care_eaushadhi.eaushadhifetchlog')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'E-Aushadhi Inward Records',
            },
        ),
        migrations.CreateModel(
            name='EAushadhiInwardRecordDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('delivery_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='eaushadhi_record_delivery', to='emr.deliveryorder')),
                ('inward_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='care_eaushadhi.eaushadhiinwardrecord')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'E-Aushadhi Record Deliveries',
            },
        ),
        migrations.CreateModel(
            name='EAushadhiInwardRecordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('inward_no', models.CharField(max_length=255)),
                ('drug_id', models.CharField(max_length=255)),
                ('drug_name', models.CharField(max_length=500)),
                ('batch_no', models.CharField(max_length=255)),
                ('manufactured_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('unit_pack', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_pack_raw', models.TextField(blank=True, null=True)),
                ('dose', models.CharField(blank=True, max_length=255)),
                ('quantity_in_units', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_received_current', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_received_initial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('warehouse_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('current_fetch_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_current_fetch', to='care_eaushadhi.eaushadhifetchlog')),
                ('initial_fetch_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_initial_fetch', to='care_eaushadhi.eaushadhifetchlog')),
                ('inward_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='care_eaushadhi.eaushadhiinwardrecord')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'E-Aushadhi Inward Record Item Batch',
            },
        ),
        migrations.CreateModel(
            name='EAushadhiInwardRecordItemDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('quantity_received', models.DecimalField(decimal_places=2, help_text='Snapshot at consumption time', max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVERSED', 'Reversed')], default='ACTIVE', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eaushadhi_item_consumptions', to='facility.facility')),
                ('inward_record_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_consumptions', to='care_eaushadhi.eaushadhiinwardrecorddelivery')),
                ('inward_record_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consumption', to='care_eaushadhi.eaushadhiinwardrecorditem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eaushadhi_consumptions', to='emr.product')),
                ('product_knowledge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eaushadhi_consumptions', to='emr.productknowledge')),
                ('supply_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eaushadhi_consumptions', to='emr.supplydelivery')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'E-Aushadhi Inward Record Item',
            },
        ),
        migrations.AddIndex(
            model_name='eaushadhifetchlog',
            index=models.Index(fields=['facility', 'inward_date', '-created_date'], name='idx_facility_inward_created'),
        ),
        migrations.AddConstraint(
            model_name='eaushadhiinwardrecord',
            constraint=models.UniqueConstraint(fields=('facility', 'inward_date'), name='uniq_facility_inward_date'),
        ),
        migrations.AddIndex(
            model_name='eaushadhiinwardrecorddelivery',
            index=models.Index(fields=['inward_record', 'deleted'], name='idx_inward_record_deleted'),
        ),
        migrations.AddConstraint(
            model_name='eaushadhiinwardrecorddelivery',
            constraint=models.UniqueConstraint(fields=('delivery_order',), name='uniq_delivery_order'),
        ),
        migrations.AddConstraint(
            model_name='eaushadhiinwardrecorditem',
            constraint=models.UniqueConstraint(fields=('inward_record', 'inward_no', 'drug_id', 'batch_no'), name='uniq_inward_drug_batch'),
        ),
        migrations.AddConstraint(
            model_name='eaushadhiinwardrecorditemdelivery',
            constraint=models.UniqueConstraint(fields=('inward_record_item',), name='uniq_inward_record_item'),
        ),
    ]
