# Generated by Django 6.0 on 2026-06-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_eaushadhi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eaushadhiinwardrecorditemdelivery',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('SOURCE_REVERSED', 'Source Reversed'), ('ACCEPTED_OVERRIDE', 'Accepted Override')], default='ACCEPTED', max_length=20),
        ),
    ]
