# Generated by Django 6.0 on 2026-06-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_eaushadhi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eaushadhiinwardrecorditemdelivery',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('REVERSED', 'Reversed'), ('ACCEPTED', 'Accepted')], default='ACTIVE', max_length=20),
        ),
    ]
