# Generated by Django 6.0 on 2026-05-30 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_eaushadhi', '0001_initial'),
        ('emr', '0077_tagconfig_metadata'),
        ('facility', '0484_remove_facility_discount_codes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EAushadhiInstituteMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('eaushadhi_institute_id', models.CharField(max_length=255)),
                ('schema_version', models.CharField(max_length=50)),
                ('credentials_ref', models.CharField(help_text='Vault reference for upstream auth', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='eaushadhi_institute_mapping', to='facility.facility')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'E-Aushadhi Institute Mappings',
            },
        ),
        migrations.CreateModel(
            name='EAushadhiInstituteSupplierMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('eaushadhi_warehouse_name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('institute_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_mappings', to='care_eaushadhi.eaushadhiinstitutemapping')),
                ('supplier', models.ForeignKey(limit_choices_to={'org_type': 'product_supplier'}, on_delete=django.db.models.deletion.PROTECT, related_name='eaushadhi_supplies', to='emr.organization')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'E-Aushadhi Institute Supplier Mappings',
            },
        ),
        migrations.AddConstraint(
            model_name='eaushadhiinstitutemapping',
            constraint=models.UniqueConstraint(fields=('facility',), name='uniq_facility_mapping'),
        ),
        migrations.AddIndex(
            model_name='eaushadhiinstitutesuppliermapping',
            index=models.Index(fields=['institute_mapping', 'deleted'], name='idx_institute_mapping_deleted'),
        ),
        migrations.AddConstraint(
            model_name='eaushadhiinstitutesuppliermapping',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('is_default', True)), fields=('institute_mapping',), name='uniq_def_institute_supplier'),
        ),
    ]
