# Generated by Django 6.0 on 2026-06-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_eaushadhi', '0002_alter_eaushadhiinwardrecorditemdelivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eaushadhiproductmapping',
            name='mapping_type',
            field=models.CharField(choices=[('BULK_IMPORT', 'Bulk Import'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20),
        ),
    ]
