# Generated by Django 6.0 on 2026-06-02 02:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_eaushadhi', '0002_eaushadhiinstitutemapping_and_more'),
        ('emr', '0077_tagconfig_metadata'),
        ('facility', '0484_remove_facility_discount_codes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EauShadhiProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('eaushadhi_drug_id', models.CharField(max_length=255)),
                ('eaushadhi_drug_name', models.CharField(max_length=500)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, help_text='Facility-specific or global if null', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eaushadhi_product_mappings', to='facility.facility')),
                ('product_knowledge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eaushadhi_mappings', to='emr.productknowledge')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'E-Aushadhi Product Mappings',
                'constraints': [models.UniqueConstraint(condition=models.Q(('facility__isnull', False)), fields=('facility', 'eaushadhi_drug_id', 'product_knowledge'), name='uniq_facility_drug_id'), models.UniqueConstraint(condition=models.Q(('facility__isnull', True)), fields=('eaushadhi_drug_id', 'product_knowledge'), name='uniq_global_drug_id')],
            },
        ),
    ]
