# Generated by Django 6.0 on 2026-06-25 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_eaushadhi', '0003_eaushadhiproductmapping_mapping_type'),
        ('emr', '0077_tagconfig_metadata'),
        ('facility', '0484_remove_facility_discount_codes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eaushadhiproductmapping',
            name='uniq_facility_drug_id',
        ),
        migrations.RemoveConstraint(
            model_name='eaushadhiproductmapping',
            name='uniq_global_drug_id',
        ),
        migrations.AddConstraint(
            model_name='eaushadhiproductmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('facility__isnull', False)), fields=('facility', 'eaushadhi_drug_id', 'product_knowledge', 'mapping_type'), name='uniq_facility_drug_pk_type'),
        ),
        migrations.AddConstraint(
            model_name='eaushadhiproductmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('facility__isnull', True)), fields=('eaushadhi_drug_id', 'product_knowledge', 'mapping_type'), name='uniq_global_drug_pk_type'),
        ),
        migrations.AddConstraint(
            model_name='eaushadhiproductmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('facility__isnull', False), ('mapping_type', 'BULK_IMPORT')), fields=('facility', 'eaushadhi_drug_id'), name='uniq_facility_drug_bulk_import'),
        ),
        migrations.AddConstraint(
            model_name='eaushadhiproductmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('facility__isnull', True), ('mapping_type', 'BULK_IMPORT')), fields=('eaushadhi_drug_id',), name='uniq_global_drug_bulk_import'),
        ),
    ]
